config/routes.rb
Tienda::Application.routes.draw do
  resources :productos


  root :to => 'home#index'
end

app/models/producto.rb
class Producto
  include Mongoid::Document
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/productos_controller.rb
class ProductosController < ApplicationController
  # GET /productos
  # GET /productos.json
  def index
    @productos = Producto.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @productos }
    end
  end

  # GET /productos/1
  # GET /productos/1.json
  def show
    @producto = Producto.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @producto }
    end
  end

  # GET /productos/new
  # GET /productos/new.json
  def new
    @producto = Producto.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @producto }
    end
  end

  # GET /productos/1/edit
  def edit
    @producto = Producto.find(params[:id])
  end

  # POST /productos
  # POST /productos.json
  def create
    @producto = Producto.new(params[:producto])

    respond_to do |format|
      if @producto.save
        format.html { redirect_to @producto, notice: 'Producto was successfully created.' }
        format.json { render json: @producto, status: :created, location: @producto }
      else
        format.html { render action: "new" }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /productos/1
  # PUT /productos/1.json
  def update
    @producto = Producto.find(params[:id])

    respond_to do |format|
      if @producto.update_attributes(params[:producto])
        format.html { redirect_to @producto, notice: 'Producto was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /productos/1
  # DELETE /productos/1.json
  def destroy
    @producto = Producto.find(params[:id])
    @producto.destroy

    respond_to do |format|
      format.html { redirect_to productos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/productos_helper.rb
module ProductosHelper
end

app/views/home/index.html.haml
%h1
  Productos
.container
  %h1 Bootstrap 3 Responsive Image Grid
  %hr/
  %h2 Non-stacking grid example
  %p.lead
    Uses the tiny
    %code .col-*
    grid classes
  %p
    This layout displays
    = succeed "." do
      %b 4 images per row
    %code img-responsive
    CSS class. As browser width shrinks, the columns and images scale down accordingly...
  .row
    .col-xs-3
      %a.thumbnail{href: "#"}
        %img.img-responsive{src: "http://placehold.it/350x150"}/
    .col-xs-3
      %a.thumbnail{href: "#"}
        %img.img-responsive{src: "http://placehold.it/350x150"}/
    .col-xs-3
      %a.thumbnail{href: "#"}
        %img.img-responsive{src: "http://placehold.it/350x150"}/
    .col-xs-3
      %a.thumbnail{href: "#"}
        %img.img-responsive{src: "http://placehold.it/350x150"}/
    .col-xs-3
      %a.thumbnail{href: "#"}
        %img.img-responsive{src: "http://placehold.it/350x150"}/
    .col-xs-3
      %a.thumbnail{href: "#"}
        %img.img-responsive{src: "http://placehold.it/350x150"}/
    .col-xs-3
      %a.thumbnail{href: "#"}
        %img.img-responsive{src: "http://placehold.it/350x150"}/
    .col-xs-3
      %a.thumbnail{href: "#"}
        %img.img-responsive{src: "http://placehold.it/350x150"}/
    .col-xs-3
      %a.thumbnail{href: "#"}
        %img.img-responsive{src: "http://placehold.it/350x150"}/
    .col-xs-3
      %a.thumbnail{href: "#"}
        %img.img-responsive{src: "http://placehold.it/350x150"}/
    .col-xs-3
      %a.thumbnail{href: "#"}
        %img.img-responsive{src: "http://placehold.it/350x150"}/
    .col-xs-3
      %a.thumbnail{href: "#"}
        %img.img-responsive{src: "http://placehold.it/350x150"}/
  %p This demonstrates a completely percentage-based responsive (A.K.A. "fluid") layout. The negative aspect of this layout is that it starts to look like the last line of an eye chart at smaller widths.
  %p Since the "eye chart" aspect isn't really a good thing, let's see how we can use Bootstrap's three powerful grid sizes to improve our design...
  %br/
  %br/
  %hr/
  %h2 4-3-2 grid example
  %p.lead Uses all 3 grid sizes
  %p
    Rather that simply scaling down image size proportionally as the browser size shrinks, a better responsive design would adjust and re-layout the image grid accordingly. The following example uses this technique. This layout shows
    %b 4 columns
    on large (ie: desktop) displays. As screen width shrinks on smaller (ie: tablets),
    %b 3 columns
    are displayed. At the smallest widths (ie: mobile phones), only
    %b 2 columns
    are displayed.
  .row
    .col-lg-3.col-sm-4.col-xs-6
      %a.thumbnail{href: "#"}
        %img.img-responsive{src: "http://placehold.it/350x150"}/
    .col-lg-3.col-sm-4.col-xs-6
      %a.thumbnail{href: "#"}
        %img.img-responsive{src: "http://placehold.it/350x150"}/
    .col-lg-3.col-sm-4.col-xs-6
      %a.thumbnail{href: "#"}
        %img.img-responsive{src: "http://placehold.it/350x150"}/
    .col-lg-3.col-sm-4.col-xs-6
      %a.thumbnail.pull-left{href: "#"}
        %img.img-responsive{src: "http://placehold.it/350x150"}/
    .col-lg-3.col-sm-4.col-xs-6
      %a.thumbnail{href: "#"}
        %img.img-responsive{src: "http://placehold.it/350x150"}/
    .col-lg-3.col-sm-4.col-xs-6
      %a.thumbnail{href: "#"}
        %img.img-responsive{src: "http://placehold.it/350x150"}/
    .col-lg-3.col-sm-4.col-xs-6
      %a.thumbnail{href: "#"}
        %img.img-responsive{src: "http://placehold.it/350x150"}/
    .col-lg-3.col-sm-4.col-xs-6
      %a.thumbnail{href: "#"}
        %img.img-responsive{src: "http://placehold.it/350x150"}/
    .col-lg-3.col-sm-4.col-xs-6
      %a.thumbnail{href: "#"}
        %img.img-responsive{src: "http://placehold.it/350x150"}/
    .col-lg-3.col-sm-4.col-xs-6
      %a.thumbnail{href: "#"}
        %img.img-responsive{src: "http://placehold.it/350x150"}/
    .col-lg-3.col-sm-4.col-xs-6
      %a.thumbnail{href: "#"}
        %img.img-responsive{src: "http://placehold.it/350x150"}/
    .col-lg-3.col-sm-4.col-xs-6
      %a.thumbnail{href: "#"}
        %img.img-responsive{src: "http://placehold.it/350x150"}/
  %p
    This improved responsive layout is achieved using Bootstrap's tiny, small and large grid sizes. By combining use of the
    = succeed "," do
      %code col-*
    %code col-sm-*
    and
    %code col-lg-*
    CSS class. Just like before, the images scale down accordingly, but now our column layout adjusts accordingly too. The
    column adjustment occurs at pre-defined "breakpoints" that are defined on the Bootstrap CSS media queries. These breakpoints align with common device sizes and widths.
  %p
    Behold the power of the Bootstrap 3's
    %b mobile first
    grid! Now we can come up with even more combinations.
  %br/
  %br/
  %hr/
  %h2 6-4-3 grid example
  %p.lead 6 columns on desktop, 4 columns on tablets, 3 columns on phones
  .row
    .col-lg-2.col-sm-3.col-xs-4
      %a{href: "#"}
        %img.thumbnail.img-responsive{src: "http://placehold.it/200x200"}/
    .col-lg-2.col-sm-3.col-xs-4
      %a{href: "#"}
        %img.thumbnail.img-responsive{src: "http://placehold.it/200x200"}/
    .col-lg-2.col-sm-3.col-xs-4
      %a{href: "#"}
        %img.thumbnail.img-responsive{src: "http://placehold.it/200x200"}/
    .col-lg-2.col-sm-3.col-xs-4
      %a{href: "#"}
        %img.thumbnail.img-responsive{src: "http://placehold.it/200x200"}/
    .col-lg-2.col-sm-3.col-xs-4
      %a{href: "#"}
        %img.thumbnail.img-responsive{src: "http://placehold.it/200x200"}/
    .col-lg-2.col-sm-3.col-xs-4
      %a{href: "#"}
        %img.thumbnail.img-responsive{src: "http://placehold.it/200x200"}/
    .col-lg-2.col-sm-3.col-xs-4
      %a{href: "#"}
        %img.thumbnail.img-responsive{src: "http://placehold.it/200x200"}/
    .col-lg-2.col-sm-3.col-xs-4
      %a{href: "#"}
        %img.thumbnail.img-responsive{src: "http://placehold.it/200x200"}/
    .col-lg-2.col-sm-3.col-xs-4
      %a{href: "#"}
        %img.thumbnail.img-responsive{src: "http://placehold.it/200x200"}/
    .col-lg-2.col-sm-3.col-xs-4
      %a{href: "#"}
        %img.thumbnail.img-responsive{src: "http://placehold.it/200x200"}/
    .col-lg-2.col-sm-3.col-xs-4
      %a{href: "#"}
        %img.thumbnail.img-responsive{src: "http://placehold.it/200x200"}/
    .col-lg-2.col-sm-3.col-xs-4
      %a{href: "#"}
        %img.thumbnail.img-responsive{src: "http://placehold.it/200x200"}/
  %hr/
  %br/
  %br/
  %h2 3-2-1 grid example
  %p.lead 3 columns on desktop, 2 columns on tablets, 1 columns on phones
  .row
    .col-lg-4.col-sm-6.col-xs-12
      %a{href: "#"}
        %img.thumbnail.img-responsive{src: "http://placehold.it/800x600"}/
    .col-lg-4.col-sm-6.col-xs-12
      %a{href: "#"}
        %img.thumbnail.img-responsive{src: "http://placehold.it/800x600"}/
    .col-lg-4.col-sm-6.col-xs-12
      %a{href: "#"}
        %img.thumbnail.img-responsive{src: "http://placehold.it/800x600"}/
    .col-lg-4.col-sm-6.col-xs-12
      %a{href: "#"}
        %img.thumbnail.img-responsive{src: "http://placehold.it/800x600"}/
    .col-lg-4.col-sm-6.col-xs-12
      %a{href: "#"}
        %img.thumbnail.img-responsive{src: "http://placehold.it/800x600"}/
    .col-lg-4.col-sm-6.col-xs-12
      %a{href: "#"}
        %img.thumbnail.img-responsive{src: "http://placehold.it/800x600"}/
    .col-lg-4.col-sm-6.col-xs-12
      %a{href: "#"}
        %img.thumbnail.img-responsive{src: "http://placehold.it/800x600"}/
    .col-lg-4.col-sm-6.col-xs-12
      %a{href: "#"}
        %img.thumbnail.img-responsive{src: "http://placehold.it/800x600"}/
    .col-lg-4.col-sm-6.col-xs-12
      %a{href: "#"}
        %img.thumbnail.img-responsive{src: "http://placehold.it/800x600"}/
  %hr/
  %br/
  %br/

app/views/layouts/application.html.haml
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1, maximum-scale=1"}
    %title= content_for?(:title) ? yield(:title) : "App_Name"
    %meta{:content => content_for?(:description) ? yield(:description) : "App_Name", :name => "description"}
    = stylesheet_link_tag :application, :media => "all"
    = javascript_include_tag :application
    = csrf_meta_tags
    = yield(:head)
  %body
    = render 'shared/header'
    #wrap
      .container
        .row
          .col-md-12
            = yield
    #push
    = render 'shared/footer'

app/views/productos/_form.html.erb
<%= form_for(@producto) do |f| %>
  <% if @producto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@producto.errors.count, "error") %> prohibited this producto from being saved:</h2>

      <ul>
      <% @producto.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/productos/edit.html.erb
<h1>Editing producto</h1>

<%= render 'form' %>

<%= link_to 'Show', @producto %> |
<%= link_to 'Back', productos_path %>

app/views/productos/index.html.erb
<h1>Listing productos</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @productos.each do |producto| %>
  <tr>
    <td><%= link_to 'Show', producto %></td>
    <td><%= link_to 'Edit', edit_producto_path(producto) %></td>
    <td><%= link_to 'Destroy', producto, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Producto', new_producto_path %>

app/views/productos/new.html.erb
<h1>New producto</h1>

<%= render 'form' %>

<%= link_to 'Back', productos_path %>

app/views/productos/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_producto_path(@producto) %> |
<%= link_to 'Back', productos_path %>

app/views/shared/_footer.haml
#footer
  %p
    © Railsgirls 2013

app/views/shared/_header.haml
#header.navbar-fixed-top
  .container-fluid
    .banner
      = image_tag 'banner.jpg'